repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.out$
      - id: end-of-file-fixer
        exclude: \.out$
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1024, --enforce-all]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.7
    hooks:
      - id: clang-format
        types_or: [c++, c]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.8
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.22.0
    hooks:
      - id: markdownlint-cli2
        args: [--config, .config/.markdownlint.yaml]
        language_version: 22.20.0
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 4.3.0
    hooks:
      - id: sqlfluff-fix
        exclude: /tests/
      - id: sqlfluff-lint
        exclude: /tests/
  - repo: local
    hooks:
      - id: no-cyrillic
        name: no cyrillic characters
        language: pygrep
        entry: '[\xd0-\xd3][\x80-\xbf]'
        types: [text]
