function(lab_current_name out_var)
    get_filename_component(name "${CMAKE_CURRENT_SOURCE_DIR}" NAME)
    set(${out_var} "${name}" PARENT_SCOPE)
endfunction()

function(lab_register target)
    lab_current_name(lab)
    if(NOT TARGET ${lab})
        add_custom_target(${lab})
    endif()
    add_dependencies(${lab} ${target})
endfunction()

function(lab_library name)
    cmake_parse_arguments(PARSE_ARGV 1 ARG "INTERFACE;SHARED" "OUTPUT_NAME" "SOURCES;LINK")
    if(ARG_INTERFACE)
        add_library(${name} INTERFACE)
        target_include_directories(${name} INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}/include")
        target_link_libraries(${name} INTERFACE ${ARG_LINK})
        return()
    endif()
    if(ARG_SHARED)
        add_library(${name} SHARED ${ARG_SOURCES})
    else()
        add_library(${name} STATIC ${ARG_SOURCES})
    endif()
    target_include_directories(${name} PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include")
    target_link_libraries(${name} PUBLIC ${ARG_LINK} PRIVATE project_options)
    if(ARG_OUTPUT_NAME)
        set_target_properties(${name} PROPERTIES OUTPUT_NAME ${ARG_OUTPUT_NAME})
    endif()
    lab_register(${name})
endfunction()

function(lab_executable name)
    cmake_parse_arguments(PARSE_ARGV 1 ARG "" "OUTPUT_NAME" "SOURCES;LINK")
    add_executable(${name} ${ARG_SOURCES})
    target_link_libraries(${name} PRIVATE project_options ${ARG_LINK})
    if(ARG_OUTPUT_NAME)
        set_target_properties(${name} PROPERTIES OUTPUT_NAME ${ARG_OUTPUT_NAME})
    endif()
    lab_register(${name})
endfunction()

function(lab_tests name)
    cmake_parse_arguments(PARSE_ARGV 1 ARG "" "LABEL" "SOURCES;LINK;BINARIES")
    add_executable(${name} ${ARG_SOURCES})
    target_link_libraries(${name} PRIVATE project_options test_support GTest::gtest_main ${ARG_LINK})
    target_compile_definitions(${name} PRIVATE
        TEST_DATA_DIR="${CMAKE_CURRENT_SOURCE_DIR}/tests/data")
    foreach(binary IN LISTS ARG_BINARIES)
        string(TOUPPER "${binary}" macro)
        target_compile_definitions(${name} PRIVATE ${macro}_PATH="$<TARGET_FILE:${binary}>")
        add_dependencies(${name} ${binary})
    endforeach()
    lab_current_name(lab)
    if(ARG_LABEL)
        gtest_discover_tests(${name} TEST_PREFIX "${lab}." DISCOVERY_MODE PRE_TEST
                             PROPERTIES LABELS ${ARG_LABEL})
    else()
        gtest_discover_tests(${name} TEST_PREFIX "${lab}." DISCOVERY_MODE PRE_TEST)
    endif()
    lab_register(${name})
endfunction()
